<?php

/**
 * @author Taha Elalami 
 */
function master_theme() {
    global $theme_key;
    return array(

        'home_slider' => array(
            'template' => 'home-slider',
            'path' => drupal_get_path('theme', $theme_key) . '/templates',
        ),
        'facebook_timeline' => array(
            'template' => 'facebook-timeline',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
        'about_us' => array(
            'template' => 'about-us',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
        'map' => array(
            'template' => 'map',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
        'contact' => array(
            'template' => 'contact',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
        'contactfav' => array(
            'template' => 'contactfav',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
        'hajj_omra' => array(
            'template' => 'hajj-omra',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
        'offrespe' => array(
            'template' => 'offrespee',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
         'hotelspe' => array(
            'template' => 'hotelspee',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),

        'we_are_favori' => array(
            'template' => 'we-are-favori',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
         'sejours' => array(
            'template' => 'sejourss',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
        'video' => array(
            'template' => 'videoo',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
         'dream' => array(
            'template' => 'dreamm',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
          'temoin' => array(
            'template' => 'temoinn',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
          'aboutfav' => array(
            'template' => 'aboutfavv',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
        'travels' => array(
            'template' => 'travels',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),

         'hotels' => array(
            'template' => 'hotels',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
          'sponsor' => array(
            'template' => 'sponsorr',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
            'investors' => array(
            'template' => 'investorss',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),

         'headhome' => array(
            'template' => 'headhome',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
          'headabout' => array(
            'template' => 'headabout',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
           'headtravel' => array(
            'template' => 'headtravel',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
           'headhotell' => array(
            'template' => 'headhotel',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
           'headcontact' => array(
            'template' => 'headcontact',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),

           'headnode' => array(
            'template' => 'headnode',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
            'headnodehotel' => array(
            'template' => 'headnodehotel',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
            'erreur_page' => array(
            'template' => 'erreur-pagee',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
            'tourislamic' => array(
            'template' => 'tourislamicc',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
            'headtourislamic' => array(
            'template' => 'headtourislamicc',
            'path' => drupal_get_path('module', 'master') . '/templates',
        ),
            'hotelhome' => array(
            'template' => 'hotelhomee',
            'path' => drupal_get_path('module', 'master') . '/templates',
        )
 
 
 

 
 
 


          






    );
}

